const e=require('express'),c=require('cors'),r=require('crypto'),p=require('path'),f=require('fs'),i=require('sql.js');
const PORT=8000,DB=p.join(__dirname,'backend','data','wellness.db'),SK='ws-key-2026';
let d;
function qA(s,q){if(!q)q=[];var t=d.prepare(s);if(q.length)t.bind(q);var w=[];while(t.step())w.push(t.getAsObject());t.free();return w;}
function qO(s,q){if(!q)q=[];var t=d.prepare(s);if(q.length)t.bind(q);var w=t.step()?t.getAsObject():null;t.free();return w;}
function qR(s,q){if(!q)q=[];d.run(s,q);}
function sv(){f.writeFileSync(DB,Buffer.from(d.export()));}
function hp(w){return r.createHash('sha256').update(w+SK).digest('hex');}
function mt(u){var j=JSON.stringify({sub:u,exp:Date.now()+604800000});return Buffer.from(j).toString('base64')+'.'+r.createHash('sha256').update(j+SK).digest('hex').slice(0,16);}
function vt(t){try{var a=t.split('.');var b=JSON.parse(Buffer.from(a[0],'base64').toString());if(r.createHash('sha256').update(JSON.stringify(b)+SK).digest('hex').slice(0,16)!==a[1]||b.exp<Date.now())return null;return b.sub;}catch(e){return null;}}
function au(q,r,n){var h=q.headers.authorization||'';if(!h.startsWith('Bearer '))return r.status(401).json({detail:'Unauthorized'});q.userId=vt(h.slice(7));if(!q.userId)return r.status(401).json({detail:'Unauthorized'});n();}
var a=e();a.use(c());a.use(e.json());a.use(e.static(p.join(__dirname,'frontend')));
a.use(function(e,q,r,n){console.error(e.message);r.status(500).json({detail:e.message});});
a.get('/api/health',function(q,r){r.json({status:'ok',version:'v2'})});
a.post('/api/auth/login',function(q,r){try{var u=q.body.username,w=q.body.password;if(!u||!w)return r.status(400).json({detail:'Required'});var u2=qO('SELECT * FROM users WHERE username=? AND hashed_password=?',[u,hp(w)]);if(!u2)return r.status(401).json({detail:'Invalid'});r.json({token:mt(u2.id),user:u2});}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.post('/api/auth/register',function(q,r){try{var u=q.body.username,w=q.body.password,n=q.body.nickname;if(!u||!w)return r.status(400).json({detail:'Required'});if(qO('SELECT * FROM users WHERE username=?',[u]))return r.status(409).json({detail:'Taken'});qR('INSERT INTO users(username,hashed_password,nickname) VALUES(?,?,?)',[u,hp(w),n||u]);var u2=qO('SELECT * FROM users WHERE rowid=last_insert_rowid()');r.json({token:mt(u2.id),user:u2});}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.get('/api/user/profile',au,function(q,r){r.json(qO('SELECT id,username,nickname,avatar,phone,constitution FROM users WHERE id=?',[q.userId]))});
a.put('/api/user/profile',au,function(q,r){try{var s=[],v=[];['nickname','phone','constitution','avatar'].forEach(function(k){if(q.body[k]!==undefined){s.push(k+'=?');v.push(q.body[k]);}});if(!s.length)return r.json({detail:'No fields'});v.push(q.userId);qR('UPDATE users SET '+s.join(',')+' WHERE id=?',v);r.json(qO('SELECT id,username,nickname,avatar,phone,constitution FROM users WHERE id=?',[q.userId]));}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.get('/api/constitution/questions',function(q,r){r.json({data:qA('SELECT * FROM constitution_questions')})});
a.post('/api/constitution/submit',au,function(q,r){try{var an=q.body.answers||{};var dm={qi:0,yang:0,yin:0,tan:0,shi:0,xue:0,qi2:0,te:0,ping:0};for(var i in an){var q1=qO('SELECT dimension FROM constitution_questions WHERE id=?',[Number(i)]);if(q1&&dm[q1.dimension]!==undefined)dm[q1.dimension]+=Number(an[i])||0;}var mx=0,rs='',mp={ping:'和平质',qi:'气虚质',yang:'阳虚质',yin:'阴虚质',tan:'痰湿质',shi:'湿热质',xue:'血瘀质',qi2:'气郁质',te:'特禀质'};for(var k in dm){if(dm[k]>mx){mx=dm[k];rs=k;}}qR('INSERT INTO constitution_records(user_id,scores,result_type) VALUES(?,?,?)',[q.userId,JSON.stringify(dm),mp[rs]||'unknown']);r.json({result:mp[rs]||'unknown',type:rs,scores:dm});}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.get('/api/constitution/history',au,function(q,r){r.json({data:qA('SELECT * FROM constitution_records WHERE user_id=? ORDER BY created_at DESC LIMIT 10',[q.userId])})});
a.get('/api/tcm/doctors',function(q,r){r.json({data:qA('SELECT * FROM tcm_doctors WHERE available=1')})});
a.get('/api/tcm/doctors/:id',function(q,r){var dr=qO('SELECT * FROM tcm_doctors WHERE id=?',[q.params.id]);if(!dr)return r.status(404).json({detail:'Not found'});r.json(dr)});
a.post('/api/tcm/consultations',au,function(q,r){try{var b=q.body;qR('INSERT INTO tcm_consultations(user_id,doctor_id,type,symptoms,constitution,price) VALUES(?,?,?,?,?,?)',[q.userId,b.doctor_id,b.type||'text',b.symptoms,b.constitution,b.price||0]);var c=qO('SELECT * FROM tcm_consultations WHERE id=(SELECT MAX(id) FROM tcm_consultations)');r.json({data:c});}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.get('/api/tcm/consultations',au,function(q,r){r.json({data:qA('SELECT * FROM tcm_consultations WHERE user_id=? ORDER BY created_at DESC',[q.userId])})});
a.get('/api/tcm/consultations/:id/messages',function(q,r){r.json({data:qA('SELECT * FROM tcm_messages WHERE consultation_id=? ORDER BY created_at ASC',[q.params.id])})});
a.post('/api/tcm/consultations/:id/messages',au,function(q,r){try{var b=q.body;qR('INSERT INTO tcm_messages(consultation_id,sender_type,sender_id,content,msg_type) VALUES(?,?,?,?,?)',[q.params.id,b.sender_type,b.sender_id||q.userId,b.content,b.msg_type||'text']);r.json({detail:'Sent'});}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.put('/api/tcm/consultations/:id/accept',function(q,r){try{qR("UPDATE tcm_consultations SET status='accepted',accepted_at=datetime('now') WHERE id=?",[q.params.id]);r.json({data:qO('SELECT * FROM tcm_consultations WHERE id=?',[q.params.id])});}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.post('/api/tcm/consultations/:id/prescribe',function(q,r){try{var b=q.body;qR('INSERT INTO tcm_prescriptions(consultation_id,doctor_id,user_id,diagnosis,prescription_text,decoction_method,dosage,precautions,days) VALUES(?,?,?,?,?,?,?,?,?)',[q.params.id,b.doctor_id,b.user_id,b.diagnosis,b.prescription_text,b.decoction_method,b.dosage,b.precautions,b.days||7]);var p=qO('SELECT * FROM tcm_prescriptions WHERE id=(SELECT MAX(id) FROM tcm_prescriptions)');qR("UPDATE tcm_consultations SET status='completed',prescription_id=? WHERE id=?",[p.id,q.params.id]);r.json({data:p});}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.post('/api/tcm/consultations/:id/rate',au,function(q,r){try{var b=q.body;qR("UPDATE tcm_consultations SET rating=?,review=?,completed_at=datetime('now') WHERE id=? AND user_id=?",[b.rating,b.review,q.params.id,q.userId]);r.json({detail:'Rated'});}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.post('/api/ai/chat',au,function(q,r){var m=(q.body.message||'').toLowerCase();var rp='';if(m.includes('hello')||m.includes('hi'))rp='你好，有什么可以帮你的？';else if(m.includes('饮食')||m.includes('吃'))rp='建议食用调和体质的食物。';else if(m.includes('运动'))rp='建议太极、散步等温和运动。';else rp='建议咨询中医师获取建议。';r.json({reply:rp,ts:Date.now()})});
a.post('/api/diary/add',au,function(q,r){try{var b=q.body;qR('INSERT INTO diary_entries(user_id,date,sleep_hours,exercise_minutes,mood_score,meal_count,water_glasses,notes) VALUES(?,?,?,?,?,?,?,?)',[q.userId,b.date,b.sleep_hours||0,b.exercise_minutes||0,b.mood_score||3,b.meal_count||3,b.water_glasses||8,b.notes||'']);r.json({detail:'Saved'});}catch(e){r.status(500).json({detail:e.message})}finally{sv()}});
a.get('/api/diary/list',au,function(q,r){r.json({data:qA('SELECT * FROM diary_entries WHERE user_id=? ORDER BY date DESC LIMIT 90',[q.userId])})});
a.get('/api/shop/products',function(q,r){r.json({data:qA('SELECT * FROM shop_products WHERE stock>0')})});
a.get('/api/vip/status',au,function(q,r){var v=qO('SELECT * FROM users WHERE id=?',[q.userId]);var vip=v.is_vip==1;if(vip&&v.vip_expires&&new Date(v.vip_expires)<new Date())vip=false;r.json({is_vip:vip,expires:v.vip_expires})});
a.get('/api/plans',function(q,r){r.json({data:qA('SELECT * FROM constitution_plans')})});
a.post('/api/pay/create',au,function(q,r){var id=(q.body||{}).plan_id||'monthly';var ps={monthly:{name:'月度会员',price:1990,days:30},quarterly:{name:'季度会员',price:4990,days:90},yearly:{name:'年度会员',price:16800,days:365}};var pl=ps[id];if(!pl)return r.status(400).json({detail:'Invalid'});var no='ORD'+Date.now()+Math.random().toString(36).slice(2,6).toUpperCase();qR('INSERT INTO pay_orders(user_id,out_trade_no,plan_id,amount,status) VALUES(?,?,?,?,?)',[q.userId,no,id,pl.price,'pending']);sv();r.json({order_no:no,mock:true,message:'模拟支付成功'});});
a.post('/api/pay/mock-complete',au,function(q,r){var no=(q.body||{}).order_no;if(!no)return r.status(400).json({detail:'Required'});var o=qO('SELECT * FROM pay_orders WHERE out_trade_no=? AND user_id=?',[no,q.userId]);if(!o)return r.status(404).json({detail:'Not found'});if(o.status!=='pending')return r.json({detail:'Done'});qR("UPDATE pay_orders SET status='paid',paid_at=datetime('now') WHERE out_trade_no=?",[no]);var pd=ps[o.plan_id]||{days:30};var ex=new Date(Date.now()+pd.days*86400000).toISOString();if(qO('SELECT * FROM vip_members WHERE user_id=?',[q.userId])){qR('UPDATE vip_members SET expires_at=? WHERE user_id=?',[ex,q.userId])}else{qR('INSERT INTO vip_members(user_id,expires_at) VALUES(?,?)',[q.userId,ex])}qR('UPDATE users SET is_vip=1,vip_expires=? WHERE id=?',[ex,q.userId]);sv();r.json({detail:'Paid',vip_expires:ex});});
a.post('/api/points/add',au,function(q,r){try{var b=q.body;qR('INSERT INTO points_log(user_id,points,action,note) VALUES(?,?,?,?)',[q.userId,b.points||0,b.action||'manual',b.note||'']);sv();r.json({detail:'Updated'});}catch(e){r.status(500).json({detail:e.message})}});
a.get('/api/points/balance',au,function(q,r){var s=qO("SELECT COALESCE(SUM(points),0) as bal FROM points_log WHERE user_id=?",[q.userId]);r.json({balance:s?s.bal:0})});
i().then(function(S){try{var data=f.readFileSync(DB);d=new S.Database(data);console.log('Loaded DB');}catch(e){d=new S.Database();console.log('New DB');}a.listen(PORT,function(){console.log('Server on '+PORT)});}).catch(function(e){console.error('Fatal:'+e.message);process.exit(1)});
